### ISSUE TITLE
Call to a member function getStatusCode() on string

### ISSUE THREAD

**Issue by phuclh** [egeloen/ivory-google-map#101]
I got the message: `Call to a member function getStatusCode() on string`

My code:

```php
$distanceMatrix = new DistanceMatrix(new CurlHttpAdapter());
$response = $distanceMatrix->process(array('Vancouver BC'), array('San Francisco'));
```

My `composer.json `file

```composer
"egeloen/google-map": "dev-master",
"widop/http-adapter": "1.0.*"
```

**Comment by geoffrey-brier** [comment]
Try using the latest version of the http-adapter (eg:  `~1.1`)

**Comment by egeloen** [comment]
We have moved to [Httplug](http://httplug.io/), so your issue is probably not an issue anymore.
