### ISSUE TITLE
`http_build_query`, Guzzle, and signing URLs for Google Maps for Work

### ISSUE THREAD

**Issue by tyler-sommer** [egeloen/ivory-google-map#102]
Hey @egeloen,

We've been using your library for a long time now. Thanks for the great work you continue to put into it!

We are now trying to make use of the `BusinessAccount` and URL signing for Google Maps for Work, but  we've hit a snag with `http_build_query()` and the Guzzle adapter. By default, `http_build_query` conforms to RFC1738 which escapes spaces as `+` characters. However, guzzle encodes the URL apparently according to RFC3986 and turns those `+` characters into `%20`.

The issue lies in the fact that because the `BusinessAccount` signs the URL with a `+` in it, but the actual URL that is sent has `%20`, the signature is not correct.

I see a couple of options for a solution:

* Change all `http_build_query` calls to use RFC3986 instead of 1738 by passing the necessary flag as the fourth parameter
* Replace `+` in `BusinessAccount`'s `$data` with `%20` prior to signing, though this option will probably affect other adapters.
* Or there may be some solution that I'm not aware of within Guzzle itself

Any advice on the matter is greatly appreciated! Thanks again.

**Comment by tyler-sommer** [comment]
FWIW, Using the CurlHttpAdapter instead works just fine. Maybe this is a non-issue

**Comment by egeloen** [comment]
We have move to [Httplug](http://httplug.io/), so your issue is probably not an issue anymore :)
