### ISSUE TITLE
Create GPS Tracker

### ISSUE THREAD

**Issue by Rezequiel** [egeloen/ivory-google-map#103]
Hi, I have some doubt about a creation of gps tracker on the map by your bundle. Let me tell what I have: 1) I have two gps device installed in two cars and sending the coordinates to my work's server and registered in one of my work's databases.
          2) I already render (and for now) the last position and the travel (based on the last 100 coordinates that one device registered)
What I need is create a gps track in the map, based on the last position that the device send me, and build the travel asynchronously without reload the page, using polyline (like I already used to build a travel with 100 last position). Sorry for my English and if I'm not clearly enough. I let you a example of what I want to do: http://hobbycoders.com/demos/gpssimulation/
Now, the question will be like; you have any idea of how can I start it or do it? I'm cain of rookie or amateur as a web developer and using Symfony, but if you can explain me something, I will understand.
Thanks for reading.

**Comment by Rezequiel** [comment]
@egeloen

**Comment by egeloen** [comment]
Honestly this is a very big topic... You can maybe use some services in the library...
