### ISSUE TITLE
Update Documentation to Indicate Return Type for Geocoder::geocode()

### ISSUE THREAD

**Issue by ReservedDeveloper** [egeloen/ivory-google-map#106]
According to documentation [here](https://github.com/egeloen/ivory-google-map/blob/master/doc/usage/services/geocoding/ivory_geocoder.md#geocoder-response), `Geocoder::geocode()` should return a `GeocoderResponse` instance. However, due to the current `{@inheritdoc}` in the docblock, the only type that is inferred as returned is `\Geocoder\Result\ResultInterface` from the main [Geocoder library](https://github.com/geocoder-php/Geocoder).

The docblock for that method should be updated to reflect the return type. Not sure if it is *always* wrapped in `GeocoderResponse`, or if there are instances in which it may return otherwise. It seems that may be the case if you do not configure a provider, but I may be off base there.

**Comment by egeloen** [comment]
The issue has been fixed in 736ef9c024c67e0e219e3936e98d5d4d49a24b8d
