### ISSUE TITLE
Could I use this source for Laravel 5.x?

### ISSUE THREAD

**Issue by cheasamnang** [egeloen/ivory-google-map#109]
Could I use this source for Laravel 5.x?

**Comment by TwinLight** [comment]
@cheasamnang, have u gone through this package with laravel 5.x? Please let me know if it support or not. Thank you

**Comment by milo526** [comment]
When using composer to get this source and installing it.
You can `use Ivory\GoogleMap;` etc to load the components.
If you use blade views return the map to your view.
Remember to use `{!! $var !!}` when loading the map in your blade view cause otherwise it'll escape the html entities.

**Comment by egeloen** [comment]
I think others have already responded to your issue. Of course, you can :)
