### ISSUE TITLE
PR for adding Api key in requests

### ISSUE THREAD

**Issue by maffpool** [egeloen/ivory-google-map#111]
Hello @egeloen,

As Google Maps services now require an Api key parameter for each request, I woul like to know if you'll accept any PR for that ?
If yes, I'll write it soon

Thanks

**Comment by remoteclient** [comment]
I'm also interested in that issue

**Comment by maffpool** [comment]
Unfortunately, the last commit of this repo is 1 year old
Maybe we could fork it, cause PRs are never merged

@remoteclient interested ?

**Comment by remoteclient** [comment]
@maffpool Maybe one of us will write the original author an email to ask if he abandoned the project. I use this with the symfony bundle and there are some other issues to make it work correctly. Unfortunately I need this only for a small part of a bigger project I am working on and I have to check if I could put time into this.

**Comment by remoteclient** [comment]
One thought... Is it not just possible to override the helper methods to append the key?

**Comment by egeloen** [comment]
This repository and the associated bundle are not maintained anymore. I'm looking for someone who would like to take the lead of these projects. Anyone interested?

**Comment by shanecp** [comment]
If anyone's interested, I've added the API Key in my fork. Won't do a PR, because this project is inactive.

https://github.com/shanecp/ivory-google-map/commit/47ca8057b0a45a72eb3626e71ce1db57756f48c1
https://github.com/shanecp/ivory-google-map

**Comment by jonny827** [comment]
@fungio  mentioned [https://github.com/egeloen/IvoryGoogleMapBundle/issues/154](in this thread) he made a fork for version 3.1  .   Maybe he would be interested in maintaining it as well...   or at least helping push some work through for the near term to get it back on its feet for the time being.

**Comment by fungio** [comment]
Indeed I made a fork for Symfony 3.1
I've also added the API Key compatibility.

**Comment by jonny827** [comment]
@egeloen I found someone to take over these projects as you requested. Please talk to @fungio

**Comment by egeloen** [comment]
Your issue has been fixed by #136 but will only be part of the 2.x version.
