### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by smartinsalmeida** [egeloen/ivory-google-map#114]
Hi, i'm trying to add a marker on the map et zoom center on it.
Here's my code

        $map = new Map();

        $map->setPrefixJavascriptVariable('map_');
        $map->setHtmlContainerId('map_canvas');

        $map->setAsync(false);
        $map->setAutoZoom(true);

        //$map->setCenter(0, 0, true); // center of world by default
        //$map->setMapOption('zoom', 3);

        //$map->setBound(-2.1, -3.9, 2.6, 1.4, true, true);

        $map->setMapOption('mapTypeId', MapTypeId::ROADMAP);
        $map->setMapOption('mapTypeId', 'roadmap');

        $map->setMapOption('disableDefaultUI', true);
        $map->setMapOption('disableDoubleClickZoom', true);
        $map->setMapOptions(array(
            'disableDefaultUI'       => true,
            'disableDoubleClickZoom' => true,
        ));

        $map->setStylesheetOption('width', '300px');
        $map->setStylesheetOption('height', '300px');
        $map->setStylesheetOptions(array(
            'width'  => '100%'
            ,'height' => '300px'
        ));

        $map->setLanguage('fr');

        // initilize geolocation
        $geocoder = new Geocoder();
        $geocoder->registerProviders(array(
            new GeocoderProvider(new CurlHttpAdapter())
        ));

        // Geocode a location
        $response = $geocoder->geocode($address);

        foreach ($response->getResults() as $result)
        {
            $location = $result->getGeometry()->getLocation();

            // Create a marker
            $marker = new Marker();

            // Position the marker
            $marker->setPosition($location);

            // Add the marker to the map
            $map->addMarker($marker);

            // Center the map on the new marker
            //$map->setCenter($location);
        }

        $mapHelper = new MapHelper();
        return ($mapHelper->render($map));

The geocoder return goods coordinates but it show me the entire ocean.
What i do wrong ? No errors are shown from PHP
Any help would be apreciated. Many Thanks

**Comment by artjomsimon** [comment]
Try uncommenting
```
//$map->setCenter($location);
```

**Comment by egeloen** [comment]
The problem with trying to manually zoom on something is you don't know how deep google can zoom on your area...

What I would do instead is to use the auto zoom feature shipped with the library which basically auto zoom on everything you add on the map:

``` php
$map = new Map()
$map->setAutoZoom(true);

$marker = new Marker(new Coordinate());

$map->getOverlayManager()->addMarker($marker);
```

Then, when you render your map you marker is automatically center as well as the zoom is automatically adjusted.
