### ISSUE TITLE
trigger click on marker on html element hover

### ISSUE THREAD

**Issue by AndyTek** [egeloen/ivory-google-map#119]
Hi guys,
this is not an issue, just my doubt.
First of all thanks for your work,
I'm trying to trigger the click event from an external js function.
usually should be something like this:

`$(".open-marker").mouseover(function(){
    var i = $(this).attr("meta-marker-id");
     google.maps.event.trigger(markers[i], 'click');
})`

Thanks in advance

**Comment by egeloen** [comment]
SInce the marker has a javascript variable, you can directly rely on it or you can rely on the map container.

Given you have a map named `my_map` and a marker named `my_marker`, then you can access then marker via `my_marler` or `my_map_container.overlays.markers.my_marker`. from anywhere in your code.

**Comment by jeremyjumeau** [comment]
As a reminder for documentation: consider using the `getVariable()` [method](https://github.com/egeloen/ivory-google-map/blob/master/src/Utility/VariableAwareTrait.php#L27) of your marker(s) if you want to further pass it in your template/html attributes.

E.G.:
```php
<?php

   //we assume that you have an entity var and a marker... 
   $entity->variable = $marker->getVariable();

   //you return this entity var to your template

```

```html
<!-- HTML -->
<a href="#" class="js-marker" data-marker="{{ entity.variable }}">Open entity marker info window</a>
```

```javascript
// jQuery
$('.js-marker').on("click", function(e) {
        e.preventDefault();
        google.maps.event.trigger(eval($(this).data('marker')), 'click');
});
```
