### ISSUE TITLE
markerclusterer_compiled.js 404

### ISSUE THREAD

**Issue by xmon** [egeloen/ivory-google-map#131]
Hi, 

the  UR "http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/src/markerclusterer_compiled.js" is a 404.

Is there any way to pass another URL in the configuration?

thanks

**Comment by xmon** [comment]
I'm trying 
https://github.com/egeloen/ivory-google-map/blob/master/doc/usage/overlays/marker_cluster.md

but tell me:
Attempted to call an undefined method named "addHelper" of class "Ivory\GoogleMap\Helper\Overlays\MarkerCluster\MarkerClusterHelper".
Did you mean to call e.g. "getHelper", "hasHelper" or "setHelper"?

any idea to solve it?

**Comment by egeloen** [comment]
The issue has been fixed in #134 but will only be part of the 2.x version.
