### ISSUE TITLE
Google Maps API error: MissingKeyMapError

### ISSUE THREAD

**Issue by NicolaeCasir** [egeloen/ivory-google-map#133]
Hello. Tell me please how can I set up API key? 

![screen shot 2016-07-22 at 4 42 55 pm](https://cloud.githubusercontent.com/assets/8903698/17058941/61ce9acc-502b-11e6-8c33-bb14c039ddcb.png)

**Comment by egeloen** [comment]
The API key support has been added in #136 but will only be part of the 2.x version.

**Comment by muspelheim** [comment]
@NicolaeCasir Hi

```log
        "simplethings/entity-audit-bundle": "^0.9.2",
        "egeloen/google-map": "2.0.x-dev",
        "egeloen/google-map-bundle": "3.0.x-dev"
```

it's versions resolve this issue in my case
