### ISSUE TITLE
Render Distance Matrix result

### ISSUE THREAD

**Issue by wwhitesoft** [egeloen/ivory-google-map#155]
Distance Matrix Service return a string like this:

object(Ivory\GoogleMap\Service\Base\Distance)#700 (2) { ["text":"Ivory\GoogleMap\Service\Base\Distance":private]=> string(6) "572 km" ["value":"Ivory\GoogleMap\Service\Base\Distance":private]=> int(572343) } 

How i can access to 572343 value?

**Comment by egeloen** [comment]
The doc was imcomplete... I just fixed it in 481ca4ea50fd6dcc69bfc535228f11bece8e6cc8

So, to answer your question:

``` php
$value = $element->getDistance()->getValue();
```

**Comment by wwhitesoft** [comment]
One more thing, if i have only 1 row in array for example Berlino to Rome, is there a way to get distance without loop trough arrays?

**Comment by egeloen** [comment]
No, there is no way... The API has been designed on top of the Google one meaning if there are an array of elements in the Google API, then, there are an array in the Ivory library.

But you can use something like:

``` php
if ($response->hasRows()) {
    $row = reset($response->getRows());
}
```
