### ISSUE TITLE
Pulled a copy on packagist, no MapHelperBuilder in package

### ISSUE THREAD

**Issue by barrychapman** [egeloen/ivory-google-map#175]
There was no MapHelperBuilder included in the download. Is that only in the 2.x release? It says that version is unstable, so just want to be sure.

-Barry

**Comment by barrychapman** [comment]
Yep. only in 2.x :)

Thanks guys!

**Comment by egeloen** [comment]
@barrychapman Yes, the library is currently rework for the upcoming 2.x version. I you start a project, you should rely on it instead of the 1.x. Composer states its is unstable but the tests suite can be trusted, everything should work.
