### ISSUE TITLE
Documentation Incorrect

### ISSUE THREAD

**Issue by barrychapman** [egeloen/ivory-google-map#176]
For the following page:

[setHtmlAttributes](https://github.com/egeloen/ivory-google-map/blob/master/doc/map.md#configure-html-attributes)

You specify at the bottom the information for `setHtmlAttributes`:

     $map->setHtmlAttributes('class', 'my-class');

Whereas - it appears that only the `$map->setHtmlAttribute()` function for setting a single attribute is the only one that takes two parameters. The `$map->setHtmlAttributes()` function takes a single array|string parameter?

Can it be clarified?

**Comment by egeloen** [comment]
@barrychapman Thanks for reporting it! There is indeed a typo in the documentation, it should be:

``` php
 $map->setHtmlAttribute('class', 'my-class');
```

**Comment by egeloen** [comment]
Your issue has been fixed in 5e87cc86a995f5d06957470b9e45ff322bfbc820
