### ISSUE TITLE
Classes Don't Exist as Shown In Documentation

### ISSUE THREAD

**Issue by djoks** [egeloen/ivory-google-map#178]
I installed the latest version of this and I was trying to follow the docs on how  o implement this and I realized soo many classes do not exist as shown in the docs.

eg. GeocoderService does not exist.

Also had an issue with this use Geocoder\Geocoder as BaseGeocoder;

Did you update the package and not the docs or am I doing something wrong here?

Basically you can see the classes that do not exist form my code:
http://prntscr.com/cbi61k

I also noticed that the readme in the docs folder seems different from what is online, anyway I floowed that now and I have this error as well:

> "Class Ivory\\GoogleMap\\Services\\Geocoding\\Geocoder cannot extend from interface Geocoder\\Geocoder",

**Comment by egeloen** [comment]
The doc on master is the doc for `dev-master` or `2.0@dev` of the library not the lastest stable release.

As you can see [here](https://github.com/egeloen/ivory-google-map/blob/master/src/Service/Geocoder/GeocoderService.php), the class you use does not exist anymore and has been moved/renamed on master.

**Comment by djoks** [comment]
Okay It would appear that the geocoder version required for this to work in v2 and not v3.   However the doc online didn't say anything initially about install geocoder v2, unless I missed it. 

Anyway thanks, everything seems to be working now. :)

**Comment by egeloen** [comment]
Hum, why do you talk about geocoder? The geocoder dependency has been dropped on master because the goal of this library is to rationalize the geocoder result from different providers whereas in this library the goal is to give you base Ivory objects which can be easily reused in the map. 

Since, it was also impossible to me to respect the contract of the Geocoder library (response object are finals and there are no interfaces to implement), I have dropped it. This is why there is no more Geocoder reference in the doc.

**Comment by djoks** [comment]
Then I dunno what to do, I installed your package and it seems to depend on geocoder.

**Comment by djoks** [comment]
Because I need the geocoding services not the map.

**Comment by egeloen** [comment]
Indeed, if you're using, the 1.4 version of the library, then, you should follow this doc: https://github.com/egeloen/ivory-google-map/tree/1.4.1

**But** I would suggest you to use the 2.x version of the library since most BC breaks as already be adressed.

**Comment by djoks** [comment]
So basically I can take out the geocoder packager I installed if I upgrade to 2.x?

**Comment by egeloen** [comment]
You have three possibilities:

 * You use the 1.4 version of the library, then you will need Geocoder 2.x
 * You use the 2.x version of the library, then you don't need Geocoder.
 * You directly use the Geocoder library.

**Comment by djoks** [comment]
Oh okay, will look into those options then, thank you very much for your time. :)
