### ISSUE TITLE
how to include the Googlemaps API key

### ISSUE THREAD

**Issue by richardNorthwind** [egeloen/ivory-google-map#179]
I've signed up and received my GoogleMaps API key but I don't know where to place it so that this composer package coding will work.  Can you please advise?

**Comment by egeloen** [comment]
@richardNorthwind FIrst, if you want to use this library with an API key, you will need to use the 2.x version of the library (`dev-master` or `2.0@dev`).

Second, to know how to respond to your question, I need to know what do you want to do with the library. Do you want to generate a map? Do you want to geocode a location? Do you want to process a directions? ...

**Comment by egeloen** [comment]
So, if you want to use the map, the api key should be configured on the api helper, see https://github.com/egeloen/ivory-google-map/blob/master/doc/helper/api.md#configure-api-key

If you're using a service (geocoeder, directions, elevations, ...), the api key should be configured on the service, see https://github.com/egeloen/ivory-google-map/blob/master/doc/service/service.md#configure-api-key
