### ISSUE TITLE
TagRenderer : UTF-8 accented letters in Autocomplete Value

### ISSUE THREAD

**Issue by lbaey** [egeloen/ivory-google-map#180]
When loading accented letters to prefill input with a value (exemple : Dakar, Sénégal), the formatter called in TagRenderer does a renderEscape() on the value, leading to display \u00xx letters to user in the input field.
Would it be possible to not escape the value of the input field of autocomplete ?
This is a very ugly fix for TagRenderer:35
```
if ($attribute === 'value') {
    $tagAttributes[] = $attribute . '="' . $value . '"';
} else {
    $tagAttributes[] = $attribute.'='.$formatter->renderEscape($value);
}
```

**Comment by egeloen** [comment]
Hum, first, thanks for reporting and there is indeed a mess here... I will fix it in a nicer way tonight.

**Comment by egeloen** [comment]
@lbaey Your issue has been fixed in the referenced PR.

**Comment by egeloen** [comment]
@lbaey If you can confirm it fixes your issue and also does not have side effect, it would be nice :)

**Comment by egeloen** [comment]
Be aware, I maintain this library but the last time I have used it in a porject was a long long time ago.

**Comment by lbaey** [comment]
Thanks ! i'll test tomorrow and keep you posted.

**Comment by lbaey** [comment]
👍 
thank you, works like a charm
