### ISSUE TITLE
InfoBox doesn't work

### ISSUE THREAD

**Issue by smaiau** [egeloen/ivory-google-map#182]
Hi egeloen,

Thank you for your work and time.
I'm trying to create an InfoWindow with the INFOBOX type.

So I included the infobox.js library, I tried different things but I can't sill figuring out why it doesn't work.

Here my code :

```
foreach ($roulottes as $roulotte) {
            /** @var Roulotte $roulotte */
            $marker = new Marker(new Coordinate($roulotte->getLatitude(), $roulotte->getLongitude()));
            //$marker->setIcon(new Icon($this->get('assets.packages')->getUrl('images/markers/' . $roulotte->getCategory()->getMarkers())));

            $infoRoulotteContent = $this->twig->render(
                'roulotte/_infoMapRoulotte.html.twig',
                ['roulotte' => $roulotte]
            );

            $infoWindow = new InfoWindow($infoRoulotteContent);
            //Here the issue
            $infoWindow->setType(InfoWindowType::INFO_BOX);
            $infoWindow->setOption('maxWidth', 400);

            $marker->setInfoWindow($infoWindow);

            $eventOpenInfoWindow = new Event(
                $marker->getVariable(),
                'click',
                sprintf(
                    'function(){
                    %s.open(%s, %s);
                }',
                    $infoWindow->getVariable(),
                    $map->getVariable(),
                    $marker->getVariable()
                )
            );

            $map->getEventManager()->addDomEvent($eventOpenInfoWindow);
            $map->getOverlayManager()->addMarker($marker);
        }
```

When i click on a marker I have this error : 
infobox.js:126 Uncaught ReferenceError: google is not defined
spot:183 Uncaught TypeError: info_window57d7a3b1bd0ee402023268.open is not a function

Any idea ?

Thank you again for your time and support,

Regards

**Comment by egeloen** [comment]
So if I understand well, you want to generate an info window which use the info box type. Then, you link this info window to a marker which is itself added to the map. Additionally, you want to open the info box when the marker is clicked. Am I right?

If yes, here a snippet (not tested):

```
$map->setAutoOpen
foreach ($roulottes as $roulotte) {
    /** @var Roulotte $roulotte */
    $marker = new Marker(new Coordinate($roulotte->getLatitude(), $roulotte->getLongitude()));

    $infoRoulotteContent = $this->twig->render(
        'roulotte/_infoMapRoulotte.html.twig',
        ['roulotte' => $roulotte]
    );

    $infoWindow = new InfoWindow($infoRoulotteContent);
    $infoWindow->setAutoOpen(true); // This option will auto open the info window when clicking on the maker.
    $infoWindow->setAutoClose(true); // This options willl auto close the info window when an other info window is open via auto open.
    $infoWindow->setType(InfoWindowType::INFO_BOX);
    $infoWindow->setOption('maxWidth', 400);

    $marker->setInfoWindow($infoWindow);
    $map->getOverlayManager()->addMarker($marker);
}
```

If this snippet does not work, there is a bug...

**Comment by egeloen** [comment]
If it does not work, I will need more informations such as symfony version, bundle version, library version, the PHP code as well as the generated javascript. Bascally everything which can help me :)

**Comment by egeloen** [comment]
Nevermind, I just added a functional tests and it fails...

**Comment by egeloen** [comment]
@smaiau I just fixed your issue in the referenced PR.

One more thing: The library has been designed in order to never get `google is not defined`... Can you please

**Comment by egeloen** [comment]
@smaiau Does the referenced PR fixes your issue?

**Comment by smaiau** [comment]
HI egeloen,

Sorry for the late reply, yeah the referenced PR fixed my issue, thank you a lot !
For the "google is not defined" it's was just a mistake in my app, I was trying to include the infobox.js which is not required so I just deleted it.

**Comment by egeloen** [comment]
Thanks for the feedback :)
