### ISSUE TITLE
Event in event its possible ?

### ISSUE THREAD

**Issue by Repti31** [egeloen/ivory-google-map#183]
Hi,

i try to write DOMEvent in Event but i dont see if is possible.

```
map57d81429bace9761461247_container.events.events.event57d8142b478e8112656223 = event57d8142b478e8112656223 = google.maps.event.addListener(marker57d8142b451f2299939227, "click", function(){
        info_window57d8142b44f07085879854.setContent("<div id='infoWindows'>test</div>");
        info_window57d8142b44f07085879854.open(map57d81429bace9761461247, this
        map57d81429bace9761461247_container.events.dom_events_once.event57d8142c47a1b569912833 = event57d8142c47a1b569912833 = google.maps.event.addDomListenerOnce(document.getElementById('infoWindows'), "click", 
                function(){
                    $.ajax({
                       //...
                    });
                }
            , false);
    );
});
```

Its possible to write this result with bundle ?

**Comment by egeloen** [comment]
You code set the content of an info window in an event, open the info window and then the code is truncated. After, you re-add an event on the map which trigger some ajax. 

So, can you please refine your question?

**Comment by Repti31** [comment]
I followed the recommendation of google for a single open windows info.
What gives with your bundle (I symfony version 3.1.4, egeloen/google-map @2.0, egeloen/google-map-bundle @egeloen 3.0).
`
$map = new Map();
$map->setHtmlId('map');
$infoWindow = new InfoWindow('');
$infoWindow->setPosition(new Coordinate());
$map->getOverlayManager()->addInfoWindow($infoWindow);
$marker = new Marker(new Coordinate());
$contentInfoWindow = '<a id='testId' href='#' data-testId=1>test content</a>';
$event = new Event(
    $marker->getVariable(),
    'click',
    'function(){
        '.$infoWindow->getVariable().'.setContent("'.$contentInfoWindow.'");
        '.$infoWindow->getVariable().'.open('
            .$map->getVariable().', this
        );
    }',
    true
);
$map->getOverlayManager()->addMarker($marker);
$map->getEventManager()->addEvent($event);
`
With this code I generate the right thing for Google to have a single open infowindows :
Now I'd like my content to be generated at the time of the event click and add AJAX function on my link has an ID "testid".
However if I add a DOMListener after, he seeks a DOM that does not yet exist as generated upon click.
Error : TypeError: a is null
code:
`
$eventDom = new Event(
    "document.getElementById('testId')",
    'click',
    "
        function(){
            var idTest = $(this).data('testId');
            $.ajax({
                url: test,
                type: 'GET',
                success: function() {
                     //...
                },
                error: function(data, statut, error) {
                   //...
               }
            });
         }
    "
);
$map->getEventManager()->addDomEvent($eventDom);
`
Example generated:
`
<script type="text/javascript">
    function ivory_google_map_map57d81429bace9761461247 () {
        //...
        map57d81429bace9761461247_container.events.dom_events_once.event57d8142c47a1b569912833 = event57d8142c47a1b569912833 = google.maps.event.addDomListenerOnce(document.getElementById('testId'), "click", 
                function(){
                    var idTest = $(this).data('testId');
                    $.ajax({
                        url: test,
                        type: 'GET',
                        success: function() {
                            //...
                        },
                        error: function(data, statut, error) {
                            //...
                        }
                    });
                }
               , false);
map57d81429bace9761461247_container.events.events.event57d8142b478e8112656223 = event57d8142b478e8112656223 = google.maps.event.addListener(marker57d8142b451f2299939227, "click", function(){
    info_window57d8142b44f07085879854.setContent("<a id='testId' href='#' data-testId=1>test content</a>");
    info_window57d8142b44f07085879854.open(map57d81429bace9761461247, this);
});
}
</script>
`
So my DOMListener should be integrated into the function of the first event but I do not see how.
code:
?

Example generated:
`
<script type="text/javascript">
    function ivory_google_map_map57d81429bace9761461247 () {
        //...
map57d81429bace9761461247_container.events.events.event57d8142b478e8112656223 = event57d8142b478e8112656223 = google.maps.event.addListener(marker57d8142b451f2299939227, "click", function(){
    info_window57d8142b44f07085879854.setContent("<a id='testId' href='#' data-testId=1>test content</a>");
    info_window57d8142b44f07085879854.open(map57d81429bace9761461247, this);

map57d81429bace9761461247_container.events.dom_events_once.event57d8142c47a1b569912833 = event57d8142c47a1b569912833 = google.maps.event.addDomListenerOnce(document.getElementById('testId'), "click", 
                function(){
                    var idTest = $(this).data('testId');
                    $.ajax({
                        url: test,
                        type: 'GET',
                        success: function() {
                            //...
                        },
                        error: function(data, statut, error) {
                            //...
                        }
                    });
                }
               , false);
});
}
</script>
`

**Comment by Repti31** [comment]
I try to understand how the trigger works because I do not know.
I started on the map google api.

**Comment by Repti31** [comment]
I found a solution that function, careful eyes :)
`
$eventDOM = new Event(
    "document.getElementById('testId')",
     'click',
     "
         function(){
             var idTest = $(this).data('testid');
             $.ajax({
                 url: test,
                 type: 'GET',
                 success: function() {
                     //...
                 },
                 error: function(data, statut, error) {
                     //...
                 }
             });
         }
         "
     );
     $domEventString = $map->getVariable().'_container.events.dom_events.event'.$eventSignalVide->getVariable().' = event'.$eventSignalVide->getVariable().' = google.maps.event.addDomListener('.$eventSignalVide->getInstance().', \'click\', '.$eventSignalVide->getHandle().');';

$event = new Event(
    $marker->getVariable(),
    'click',
    'function(){
        '.$infoWindow->getVariable().'.setContent("'.$contentInfoWindow.'");
        '.$infoWindow->getVariable().'.open('
            .$map->getVariable().', this
        );
        '.$domEventString.'
    }',
    true
);
`

**Comment by egeloen** [comment]
If you're using the bundle, I have probably a better solution for you if you want to render an event inside an event, you can reuse the `*EventRenderer` which have the responsibility to render events. The service name in Symfony are:

 - ivory.google_map.helper.renderer.event.dom_event
 - ivory.google_map.helper.renderer.event.dom_event_once
 - ivory.google_map.helper.renderer.event.event
 - ivory.google_map.helper.renderer.event.event_once

Then, we can imagine introduce a factory which have the responsibilty to generate your main event. In this factory you inject the event renderer and you render the sub event when creating the main event.

**Comment by Repti31** [comment]
Ok, thanks for help !
