### ISSUE TITLE
cURL error 60: SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by btamas27** [egeloen/ivory-google-map#186]
Hey.
I wanted to use the directions, but i got this error: 
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

![image](https://cloud.githubusercontent.com/assets/13316330/18631500/059c6210-7e7b-11e6-9737-e5302b9f44d1.png)

I've installed: php-http/guzzle6-adapter and php-http/message

**Comment by btamas27** [comment]
I figured it out :P

**Comment by vikdb** [comment]
Having the same problem.. care to share the solution?

**Comment by egeloen** [comment]
You have probably an issue with your local cacert config. Download http://curl.haxx.se/ca/cacert.pem and configure it in your php.ini with: `curl.cainfo = "[pathtothisfile]\cacert.pem"`. Then, the problem should be solved.
