### ISSUE TITLE
Provider

### ISSUE THREAD

**Issue by djoks** [egeloen/ivory-google-map#190]
I'm a bit confused about something, does this use google maps? Reason for asking is I typed an address location in google map and got a result but when I passed that same address to the geocoder I got no result.

Can you please explain this to me and if there is a way to get more accurate results.

**Comment by egeloen** [comment]
Obviously it uses the google maps service :) Can you please provide your request informations?

**Comment by egeloen** [comment]
@djoks Any news?

**Comment by egeloen** [comment]
ping @djoks

**Comment by djoks** [comment]
Alright, sorry been busy.  I just passed the same address I used in google maps to the api, which is why I'm wondering why I didn't get the same results.  By request info what do you mean?

**Comment by egeloen** [comment]
I mean what do you put in the text field :) Basically what is the address you use when you're doing your test in order to reproduce it on my side.

**Comment by egeloen** [comment]
ping @djoks :)

**Comment by egeloen** [comment]
Closing for now as there is no feedbacks. If you want you can reopen it with the input you use (ie. the address you query on the geocoder).
