### ISSUE TITLE
Problem with Infowindow

### ISSUE THREAD

**Issue by olivier-rey** [egeloen/ivory-google-map#191]
Hello,

I try to link infowindow with a marker and display it but i failed to define it's position and to display it on mouseover.

```
        ....
        $infoWindow = $this->addInfoWindow($activite, $page, new Coordinate($lat, $lng));
        $marker->setInfoWindow($infoWindow);

        $mouseouthandle = 'function(){'.$infoWindow->getVariable().'.close()}';
        $mouseoutevent = new Event($marker->getVariable(), MouseEvent::MOUSEOUT , $mouseouthandle);

        $this->map->getEventManager()->addDomEvent($mouseoutevent);

        $clickhandle = 'function(){url = Routing.generate("show_activite", { id_activite:' . $activite->getId() . '});'
                . 'window.location.href=url;}';

        $clickevent = new Event($marker->getVariable(), 'click', $clickhandle);

        $this->map->getEventManager()->addDomEvent($clickevent);
        return $marker;
    }

    private function addInfoWindow($element, $page, $coordinate)
    {

        $content = $this->setInfoWindowContent($element, $page);
        $infoWindow = new InfoWindow($content, InfoWindowType::DEFAULT_, $coordinate);
        $infoWindow->setPixelOffset(new Size(1.1, 2.1));
        $infoWindow->setOpen(false);
        $infoWindow->setAutoOpen(true);
        $infoWindow->setOpenEvent(MouseEvent::MOUSEOVER);
        $infoWindow->setAutoClose(true);
        $infoWindow->setOptions(array(
            'disableAutoPan' => true,
            'zIndex' => 10,
            'borderRadius' => 10,
        ));

        return $infoWindow;
    }
```

if i change setOpen to true, i can display it and mouseout event works, but no position.
I also tried to display it on event without success : 

```
        $mouseoverhandle = 'function(){'.$infoWindow->getVariable().'.open()}';
        $mouseoverevent = new Event($marker->getVariable(), MouseEvent::MOUSEOVER, $mouseoverhandle);

        $this->map->getEventManager()->addDomEvent($mouseoverevent);
```

I use symfony 2.8.12 , egeloen/google-map dev-master 5d87649 and egeloen/google-map-bundle dev-master b664856

Any idea ?

Thanks for your support,

Olivier

**Comment by egeloen** [comment]
After reading your code, I think you misunderstood the way to position an info window. When you want to put an info window on a map you have two possibilities:

 * Put the info window on the map directly with a position on the info window.
 * Put the info window on a marker with a position on the marker.

So, here, you should place your marker on a specific position and link your info window to it. Additionally, enable auto open/close as well as custom mouse event (hover).

**Comment by egeloen** [comment]
ping @olivier-rey :)

**Comment by olivier-rey** [comment]
Hello Eric,
Thanks for your feedback, and sorry for the late reply :)
I agree on your comment on my code, I tried many things, and let by mistake the coordinate as argument to create a new infowindow.
Whatever even without this, the functions setAutoOpen, setAutoClose, and setOpenEvent doesn't seems to work...

Eventually i did it manually with
```
        $mouseoverhandle = 'function(){'
                .$infoWindow->getVariable().'.open('.$this->map->getVariable().','.$marker->getVariable().');'
                . '}';
        $mouseoverevent = new Event($marker->getVariable(), MouseEvent::MOUSEOVER, $mouseoverhandle);
        $this->map->getEventManager()->addDomEvent($mouseoverevent);
```
Thanks,

**Comment by egeloen** [comment]
@olivier-rey Are you using the bundle? If yes, you should have probably hit https://github.com/egeloen/IvoryGoogleMapBundle/pull/184 which have been fixed.

**Comment by olivier-rey** [comment]
@egeloen Yes, problem solved, thanks for all :)

**Comment by egeloen** [comment]
:+1: Thanks for the feedback! :)
