### ISSUE TITLE
Map and Api code correctly rendered on page but map will not show

### ISSUE THREAD

**Issue by satyago** [egeloen/ivory-google-map#193]
The code for Map and API are developed closely to the new documentation and rendered correctly on the page, but the maps function is not invoked after all parts are loaded and therefore no map is showing.

What's wrong with the code?

Missing any settings on the PHP side or client side code?

Below is a 'working' example, illustrating the issue (of course to be run on a server and `GOOGLE_API_KEY` requires a replacement with your own key first).

The map will not show until you manually invoke the `ivory_google_map_map_0()` function in the browser console. Why isn't this working through the async API loader?

```HTML
<!DOCTYPE html>
<html lang="de">
    <head>
        <meta charset="utf-8">
    </head>
    <body>

        <!-- Generated Map Code -->
        <div id="canvas_0" style="width: 100%;height: 400px;"></div>
        <style type="test/css">
            #canvas_0 {
                height: 400px;
                width: 100%;
                min-width: 100px;
            }
        </style>
        <script type="text/javascript">
            function ivory_google_map_map_0 () {
                map_0_container = {
                    "base": {
                        "coordinates": [],
                        "bounds": [],
                        "points": [],
                        "sizes": []
                    },
                    "map": null,
                    "overlays": {
                        "circles": [],
                        "encoded_polylines": [],
                        "ground_overlays": [],
                        "polygons": [],
                        "polylines": [],
                        "rectangles": [],
                        "info_windows": [],
                        "info_boxes": [],
                        "marker_images": [],
                        "markers": [],
                        "marker_cluster": null
                    },
                    "layers": {
                        "heatmap_layers": [],
                        "kml_layers": []
                    },
                    "events": {
                        "dom_events": [],
                        "dom_events_once": [],
                        "events": [],
                        "events_once": []
                    },
                    "functions": []
                };
                map_0_container.functions.info_windows_close = function () {};
                map_0_container.functions.to_array = function (o) {
                    var a = [];
                    for (var k in o) {
                        a.push(o[k]);
                    }
                    return a;
                };
                map_0_container.base.coordinates.coordinate5819b66ba83c8555705487 = coordinate5819b66ba83c8555705487 = new google.maps.LatLng(51.1915165, 6.7712304, true);
                map_0_container.map = map_0 = new google.maps.Map(document.getElementById("canvas_0"), {
                    "mapTypeId": google.maps.MapTypeId.ROADMAP,
                    "zoom": 15,
                    "disableDefaultUI": true,
                    "disableDoubleClickZoom": true
                });
                map_0_container.overlays.markers.marker_0 = marker_0 = new google.maps.Marker({
                    "position": coordinate5819b66ba83c8555705487,
                    "map": map_0,
                    "animation": google.maps.Animation.DROP,
                    "clickable": false,
                    "flat": true
                });
                map_0.setCenter(coordinate5819b66ba83c8555705487);

            }
        </script>

        <!-- Generated API Code -->
        <script type="text/javascript">function ivory_google_map_load(){google.load("maps","3",{"other_params":"language=de&key=GOOGLE_API_KEY","callback":ivory_google_map_init})};function ivory_google_map_init_source(src){var script=document.createElement("script");script.type="text/javascript";script.async=true;script.src=src;document.getElementsByTagName("head")[0].appendChild(script);};function ivory_google_map_init_requirement(c,r){if(r()){c();}else{var i=setInterval(function(){if(r()){clearInterval(i);c();}},100);}};function ivory_google_map_init(){};ivory_google_map_init_source("https://www.google.com/jsapi?callback=ivory_google_map_load");</script>


    </body>
</html>
```

**Comment by egeloen** [comment]
FIrst, thanks for your detailled bbug report! There is indeed somethign wrong in the generated code... The init caallback is empty and for now, I don't know why:

``` js
function ivory_google_map_init(){};
```

which should be:

``` js
function ivory_google_map_init(){ivory_google_map_map_0();};
```

Let me debug it and I will come back here with more informations and maybe a patch...

**Comment by egeloen** [comment]
@satyago Can you please copy/paste the code used to generated this code?

**Comment by satyago** [comment]
Sure. Could only extract the crucial parts; the rest is automated via model and controller classes and loops within a Laravel application. Instead of returning to the template I now used `echo` and removed a few other parts. Hope this helps anyways; also hoping there's no errors on my extract / usage.

            $addressArray = [
                '767 5th Ave',
                'New York',
                'NY 10153',
                'USA'
            ];

            // create human format address string
            $full_address_string = implode(' ',  $addressArray);

                // Geocode
                $geocoder           = new GeocoderService(new Client(), new GuzzleMessageFactory());
                $request            = new GeocoderAddressRequest($full_address_string);
                $response           = $geocoder->geocode($request);
                $responseResults    = $response->getResults();
                $addressDetails     = array_shift($responseResults);
                $addressCoordinates = $addressDetails->getGeometry()->getLocation();

            // internal map name
            $mapName = "map_0";

            // create map
            $map = new Map();
            $map->setHtmlId($mapName . '_canvas');
            $map->setVariable($mapName . '_map');
            $map->setCenter($addressCoordinates); // set location
            $map->setAutoZoom(false);

            $map->setStylesheetOptions([
                'height'    => '400px',
                'width'     => '100%',
                'min-width' => '100px',
            ]);

            $map->setMapOptions([
                'zoom'                   => 15,
                'disableDefaultUI'       => true,
                'disableDoubleClickZoom' => true,
                'mapTypeId'              => 'roadmap',
            ]);

            // render
            $mapHelperBuilder = MapHelperBuilder::create();
            $mapHelperBuilder->getFormatter()->setDebug(true);
            $mapHelperBuilder->getFormatter()->setIndentationStep(4);
            $mapHelper = $mapHelperBuilder->build();

            echo $mapHelper->render($map);

        $apiHelperBuilder = ApiHelperBuilder::create();
        $apiHelperBuilder->setKey(env('GOOGLE_API_KEY', false));
        $apiHelperBuilder->setLanguage('de');

        $apiHelper = $apiHelperBuilder->build();

        echo $apiHelper->render($map);

**Comment by egeloen** [comment]
Thanks for your detailled report one more time :) Now let me some time to debug this piece of code :)

**Comment by egeloen** [comment]
I just push your code in https://github.com/egeloen/ivory-google-map-issue-193 and it works... Can you give it a try? Just need to install dependencies and replace my hardcoded api key (already deleted) by your own. Unfortunatelly, it seems the issue is on your side

**Comment by satyago** [comment]
Sh* … I just noticed the issue was, that in production the API Helper object received the rendered map and not the map object itself. What led to this confusion is a mystery. I apologise for the trouble and appreciate your effort ! Thank you !

**Comment by egeloen** [comment]
You're welcome! Always a pleasure to close an issue :)
