### ISSUE TITLE
Laravel 5.3 help with library install - missing Builder folder from src/Helper/

### ISSUE THREAD

**Issue by milosstanojevic** [egeloen/ivory-google-map#195]
Hello, i have some issue with package instalation on laravel 5.3.

Installed the package with composer require egeloen/google-map. In vendor files I have these:
![1](https://cloud.githubusercontent.com/assets/16463837/20230520/c167961c-a85c-11e6-896c-8e9da4781d5f.JPG)

I am trying to render a map with helper, but builder folder is missing. 
I have a error: 

> Class 'Ivory\GoogleMap\Helper\Builder\MapHelperBuilder' not found

I tried google for help but have no luck. If you can please help me. Thanks in advance.

**Comment by egeloen** [comment]
Hey! Thanks for your report! Can you please copy/paste your composer.json file?

**Comment by milosstanojevic** [comment]
I attached the composer.json file in this zip. If you need anything else I will provide. Thanks.
[composer.zip](https://github.com/egeloen/ivory-google-map/files/587267/composer.zip)

**Comment by egeloen** [comment]
The issue is you rely on the stable version of the library (1.x) whereas the doc you browse online is the dev-master one (2.x). I recommend you to rely on dev-master since I should release an alpha in few weeks.

**Comment by milosstanojevic** [comment]
Ok, thanks. I will close this issue now.
