### ISSUE TITLE
Inconsistency on doc Distance Matrix API Service

### ISSUE THREAD

**Issue by diegosurita** [egeloen/ivory-google-map#198]
The [Distance Matrix API documentation](https://github.com/egeloen/ivory-google-map/blob/master/doc/service/distance_matrix/distance_matrix.md) has a class called `DistanceMatrixService` on section **Build** that don't exist in the library.

Could someone fix it, please?

**Comment by egeloen** [comment]
Hum, the class exists: https://github.com/egeloen/ivory-google-map/blob/master/src/Service/DistanceMatrix/DistanceMatrixService.php What version of the library do you use? 1.x or 2.x (the online doc is the 2.x one).

**Comment by diegosurita** [comment]
I'm using version 1.x. It'd be good to mention what version the documentation is about.

Thanks.

**Comment by egeloen** [comment]
Fixed by d7d8bd07e099a32afbfe92a91c0b57afe664727a.
