### ISSUE TITLE
parse error in Helper Collector Overlay InfoWindowCollector

### ISSUE THREAD

**Issue by MatthewReed** [egeloen/ivory-google-map#199]
egeloen/ivory-google-map version 2.x.

On Linux Ubuntu 16.04 PHP 5.6.28-1+deb.sury.org~xenial+1 Symfony 2.8.14
I find the following error when I try to build a map:

Parse Error: syntax error, unexpected '|', expecting ')' 
in vendor/egeloen/google-map/src/Helper/Collector/Overlay/InfoWindowCollector.php at line 88

public function collect(
        Map $map,
        array $infoWindows = [],
        **$strategy = self::STRATEGY_MAP | self::STRATEGY_MARKER**
    )

is not correctly parsed, neither it is wraping in parentheses like $strategy = (self::STRATEGY_MAP | self::STRATEGY_MARKER).

A feasible solution:

public function collect(
        Map $map,
        array $infoWindows = [],
        $strategy = null
    )
{
    if (empty($strategy))
    {
        $strategy = self::STRATEGY_MAP | self::STRATEGY_MARKER;
    }
...
...
...
}

**Comment by egeloen** [comment]
@MatthewReed Thanks for reporting this issue! Can you please provide a patch in order to fix it?

**Comment by MatthewReed** [comment]
Patch provided. Travis test not passed due to errors in other classes.
