### ISSUE TITLE
Feature request: Static map

### ISSUE THREAD

**Issue by Rhinni** [egeloen/ivory-google-map#201]
I would like to create a static map so I can show a preview of my map without the actual performance impact of showing the complete map (sometimes over 2000 markers at a time). 

Implementing the option to render a map build with ivory google map as a static map would be amazing.

The Google API in question: https://developers.google.com/maps/documentation/static-maps/intro

**Comment by egeloen** [comment]
@Rhinni I just added support for static map rendering in the referenced PR. Anyway, according to your use case, I hope it will fit the spec since the url length is limited to 8192 chars...

**Comment by Rhinni** [comment]
@egeloen Great thanks! Can't wait to test this. I will have to play around with the limited url length and see what's preferred in the case it exceeds the limit (no markers at all or just a portion). Either way I'm happy you've added the support!
