### ISSUE TITLE
Auto fitting bounds doesn't work

### ISSUE THREAD

**Issue by davidromani** [egeloen/ivory-google-map#211]
Hello again.

I'm trying to use this solution https://github.com/egeloen/ivory-google-map/blob/master/doc/map.md#fitting-a-bound-which-extends-overlayslayers to show all markers auto-centered in my map.

```php
use Symfony\Bundle\FrameworkBundle\Templating\Helper\AssetsHelper;

class GmapService
{
    /** @var AssetsHelper */
    private $ah;

    public function __construct(AssetsHelper $ah)
    {
        $this->ah = $ah;
    }

    public function getPartnerAdavantatgesMap(array $items)
    {
        $map = new Map();
        $map->setStylesheetOption('width', '100%');
        $map->setStylesheetOption('height', '450px');
        $map->setMapOptions([
            'mapTypeId' => MapTypeId::ROADMAP,
            'zoom' => 5,
        ]);

        /** @var Company|Activity $item */
        foreach ($items as $item) {
            $coordinate = new Coordinate($item->getLat(), $item->getLng());
            $marker = new Marker(
                $coordinate,
                Animation::DROP,
                new Icon($this->ah->getUrl('img/kinder-marker.png'))
            );
            $map->getOverlayManager()->addMarker($marker);
        }

        $map->setAutoZoom(true);
        $map->getOverlayManager()->getMarkerCluster()->setOption('imagePath', '/img/gmaps/m');
        $map->getOverlayManager()->getMarkerCluster()->setType(MarkerClusterType::MARKER_CLUSTERER);

        return $map;
    }
```

And after render the map, all markers (and clusterer icons) are showing well, but my map never apply atuo-center...

**Comment by egeloen** [comment]
The problem is pretty simple, you need to enable the auto zoom **before** adding your marker. Basically, the overlay manager decides if it needs to "extend" the overlay item at the moment you add it. It allows for example to center the map on 3 markers and add other markers without auto zooming on them...

**Comment by davidromani** [comment]
Thx! 

Maybe it's important to write in doc, I've spend 3 hours with this...

**Comment by egeloen** [comment]
@davidromani Thanks for your feedback! I have improved it in dd50f06 I hope it is now more understandable...
