### ISSUE TITLE
type-o in documentation

### ISSUE THREAD

**Issue by snoop168** [egeloen/ivory-google-map#219]
https://github.com/egeloen/ivory-google-map/blame/master/doc/installation.md#L45

your handle is misspelled... Took me a few minutes to find that wondering why I couldnt get the package to install.

**Comment by egeloen** [comment]
@snoop168 Thanks for your feedback! Sorry for losing your time but it's funny I'm able to make a typo in my own name... Can you provide a PR? otherwise I will fix it later.

**Comment by egeloen** [comment]
I fixed it in d2507c2
