### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by peterjaap** [egeloen/ivory-google-map#226]
In marker.md, under [Configure shape](https://github.com/egeloen/ivory-google-map/blob/master/doc/overlay/marker.md#configure-shape), it says `setIcon` instead of `setShape`.

**Comment by egeloen** [comment]
@peterjaap Thanks for your feedback! Can you open a PR to fix it?

**Comment by egeloen** [comment]
The issue has been fixed by 28b02ec5c5c47c60ce533d60c32416a21c797164
