### ISSUE TITLE
Static map styles

### ISSUE THREAD

**Issue by jrswgtr** [egeloen/ivory-google-map#229]
I am wondering if i can generate a static map with custom styles. I cannot find anything in the documentation or source code. Thank you in advance.

**Comment by egeloen** [comment]
@jrswgtr Everything is supported in the static map... except custom styles... :(

**Comment by jrswgtr** [comment]
@egeloen Thanks for your reply. I guess i will have to look for a different solution.

**Comment by jrswgtr** [comment]
@egeloen To me it does not seem too hard to build this feature. At the moment I am quite busy but I will be looking into it and maybe in the future I can contribute.

**Comment by egeloen** [comment]
:+1:

**Comment by jrswgtr** [comment]
I understand. Great work anyway, love the library!

**Comment by jrswgtr** [comment]
I wrote this little class to generate a query string and put it after the request URL. Not the mos elegant solution, but it did the job for me!

`class StyleBuilder
{
	private $styles = [];

	public function addStyle(array $style = [])
	{
		$this->styles[] = $style;
		return $this;
	}

	public function setStyles(array $styles = [])
	{
		$this->styles = $styles;
		return $this;
	}

	public function getStyles()
	{
		return $this->styles;
	}

	public function getQueryString($mapUrl = '')
	{
		$styleStrings = [];
		foreach ($this->styles as $style) {
			$styleStrings[] = 'style=' . str_replace('=', ':', http_build_query($style,'','|'));
		}

		$queryString = '&' . implode($styleStrings, '&');
		$url = $mapUrl . $queryString;
		return $url;
	}
}`

**Comment by egeloen** [comment]
@jrswgtr Thanks, are you OK if I take your work and integrate it in the library?

**Comment by jrswgtr** [comment]
@egeloen Sure, it would be an honor!
