### ISSUE TITLE
Add colon to end of encoded polyline when making request to distance matrix api

### ISSUE THREAD

**Issue by dergus** [egeloen/ivory-google-map#240]
Distance matrix service requires encoded polylines in the following format:
> Encoded polylines must be prefixed with enc: and followed by a colon (:).For example: origins=enc:gfo}EtohhU: (https://developers.google.com/maps/documentation/distance-matrix/intro)

but the lib doesn't add add `:` to the end of encoded polyline which makes requests invalid

**Comment by egeloen** [comment]
@dergus Thanks for your report! Can you submit a PR to fix it?

**Comment by dergus** [comment]
@egeloen of course!

**Comment by egeloen** [comment]
@dergus Thx!
