### ISSUE TITLE
Add egeloen/serializer to composer dependencies

### ISSUE THREAD

**Issue by dergus** [egeloen/ivory-google-map#241]
`egeloen/serializer` used in `AbstractSerializableService` and if you dont require it manually call to  `AbstractSerializableService` subclasses will end in fatal error which is't very easy to find why. I suggest to add it to require section of composer from require-dev

**Comment by egeloen** [comment]
@dergus `egeloen/serializer` is an optional dependency because for example, you can render a map without using Google Map services such as Geocoder, Distance Matrix, etc.

**Comment by dergus** [comment]
@egeloen Well, that's my fault I did not read the dependencies section)
