### ISSUE TITLE
Get location by Ip ?

### ISSUE THREAD

**Issue by xorgxx** [egeloen/ivory-google-map#244]
Hi i have just install your bundle and it since to all work well.

i have question : it's possible to get the geolocazation by IP ? if yes how.

Thank

**Comment by egeloen** [comment]
@xorgxx I'm not sure Google allows to geocode by IP... Can you point me the official doc about this feature?

**Comment by xorgxx** [comment]
ok i deed not realy see in PHP but it since to have in Js : 
```
<!DOCTYPE html>
<html>
<body>

<p>Click the button to get your coordinates.</p>

<button onclick="getLocation()">Try It</button>

<p id="demo"></p>

<script>
var x = document.getElementById("demo");

function getLocation() {
    if (navigator.geolocation) {
        navigator.geolocation.watchPosition(showPosition);
    } else { 
        x.innerHTML = "Geolocation is not supported by this browser.";}
    }
    
function showPosition(position) {
    x.innerHTML="Latitude: " + position.coords.latitude + 
    "<br>Longitude: " + position.coords.longitude;
}
</script>

</body>
</html>
```
maybe possible to integrete in your bundle ?
Thnak

**Comment by egeloen** [comment]
It is not related to Google Maps but related to your browser, so honestly, I'm not in favor of adding it to the bundle (and looking to the code, it's so simple that you can manage it yourself in your code very very easily).

**Comment by xorgxx** [comment]
it is very true!! Thank
