### ISSUE TITLE
Call to undefined method Ivory\GoogleMap\Map::setStylesheet()

### ISSUE THREAD

**Issue by ChrisMwai** [egeloen/ivory-google-map#246]
Following your very brief documentation, I'm running into a lot of errors just to show a simple map in laravel. The issue presents itself when I have the following lines of code present in my controller:

$map->setStylesheet('position', 'inherit');
$map->setStylesheet('width', '100%');
$map->setStylesheet('height', 'calc(100vh - 170px)');

$apiHelper = ApiHelperBuilder::create()->build();
$apiHelper->setKey('my_key_here');

I am inclined to think there's a class I'm not loading like so:
use Ivory\GoogleMap\?????

Without those lines, I'm ending up with a 300px x 300px map THAT'S HIDDEN BEHIND THE LEFT SIDEBAR.

**Comment by egeloen** [comment]
@ChrisMwai Thanks for your feedback! The method is named `setStylesheetOption` (https://github.com/egeloen/ivory-google-map/blob/master/src/Map.php#L436) Can you submit a PR which fixes the doc you have used?

**Comment by ChrisMwai** [comment]
@egeloen That error has been resolved (I presume since only one error is showing now and I cannot test untill its fixed).

Call to undefined method Ivory\GoogleMap\Helper\Builder\MapHelperBuilder::setKey()

**Comment by ChrisMwai** [comment]
Fixed it. Was an error on my end. I had called the method on MapHelperBuilder instead of ApiHelperBuilder
