### ISSUE TITLE
Elevation API support? 

### ISSUE THREAD

**Issue by allmarkedup** [egeloen/ivory-google-map#39]
Just started using this library and it's really excellent, impressed with how well thought through and documented everything is. Great job!

I was wondering if you had any plans to add support for the [Elevation API](https://developers.google.com/maps/documentation/elevation/)? I need it for the project I'm working on currently - if you aren't planning on adding it any time soon I will try and fork it and add it myself but just wanted to check it's not something you've already got in the pipeline, as it seems to be the only major service missing that I can see.

Many thanks for putting this together! Has saved me loads of time already.

**Comment by migmolrod** [comment]
I'd like to have this too.

**Comment by egeloen** [comment]
I see that the API elevation requires an API key. Does anyone know if I can get an API key for testing purpose without having to pay anything? Basically, If I want to add this feature, I will need an API key...

**Comment by egeloen** [comment]
Your issue has been fixed in #168 but will only be part of the 2.x version.
