### ISSUE TITLE
Add DirectionsRenderer

### ISSUE THREAD

**Issue by nysander** [egeloen/ivory-google-map#68]
Is it planned? if yes when it will hit repository?

**Comment by egeloen** [comment]
I have read the doc about `DirectionsRenderer` in the Google doc. It seems this class is only useful when using the directions service. So, how would you like to integrate this feature? It's not obvious to me...

**Comment by egeloen** [comment]
For the record, I see the feature this way:

```
$response = $direction->process($request);

$map = new Map():
$map->getDirectionManager()->addDirection(new Direction($response));

echo $mapHelper->render($map);
echo $apiHelper->render([$map]);
```

Then, the map is rendered with a direction renderer rendering the direction result.

**Comment by egeloen** [comment]
@nysander @codefields I know it's a very old issue but can you give me feedback on what would you expect for the `DirectionsRenderer`?

**Comment by nysander** [comment]
@egeloen atm project in which I wanted to use this feature is abandoned and will not be revived in near future, so I even do not remember how I wanted this to work for me. sorry

**Comment by egeloen** [comment]
No, pb. Then, closing and if someone needs this feature, please re-open an issue in order to discuss it.
