### ISSUE TITLE
[question] Is it possible to include custom map styles?

### ISSUE THREAD

**Issue by tomvo** [egeloen/ivory-google-map#78]
Like this: https://developers.google.com/maps/documentation/javascript/styling?csw=1
?

If not, where would something like this fit in the code?

**Comment by theobalkwill** [comment]
Hi, I'm also trying to use snazzy maps themes with your bundle but I haven't figured how to make it work yet. I tryed this:

$map->setMapOption('styles', array( 
  "featureType"=>"water","elementType"=>"geometry.fill","stylers"=>array("color"=>"#d3d3d3"),
  "featureType"=>"transit","stylers"=>array("color"=>"#808080","visibility"=>"off"),
 "featureType"=>"road.highway","elementType"=>"geometry.stroke","stylers"=>array("visibility"=>"on","color"=>"#b3b3b3"),
...
  "featureType"=>"road","elementType"=>"labels.icon","stylers"=>array("visibility"=>"off"),
  "featureType"=>"poi","elementType"=>"geometry.fill","stylers"=>array("color"=>"#dadada")
));

But no success...

Could you just give me an example using even the most basic theme?

**Comment by starkj** [comment]
Google Maps API expects an js array as value for the "stylers" attribute:

```javascript
var styles = [
  {
    stylers: [
      { hue: "#00ffe6" },
      { saturation: -20 }
    ]
  },{
    featureType: "road",
    elementType: "geometry",
    stylers: [
      { lightness: 100 },
      { visibility: "simplified" }
    ]
  },{
    featureType: "road",
    elementType: "labels",
    stylers: [
      { visibility: "off" }
    ]
  }
];

map.setOptions({styles: styles});
```
To achieve this, you have to do something like that:

```php
$map->setMapOption('styles' , array(
    array('featureType' => 'water', 'stylers' => array(array('color' => '#00FF00'))),
    array('stylers' => array(array('hue' => "#00ffe6", 'saturation' => '-20')))
));
```

**Comment by xmon** [comment]
You can use this online tool: http://php.fnlist.com/php/json_decode or this snippet:
```php
        $json = '...your json...';
        $assoc = true;
        $style = json_decode($jsonDia, $assoc);
        $map->setMapOption('styles', $style);
```
