### ISSUE TITLE
Markers bound fitting is not working.

### ISSUE THREAD

**Issue by stanivanovpro** [egeloen/ivory-google-map#80]
I'm using IvoryGoogleMapBundle 2.1 with bounds that should fit marker extends but it's not working.

I tried to investigate the issue and it seems that JavaScript map.fitBounds(bound) should be called after all extends are added to bound object. For now this line is added by MapHelper::renderMapBound method which is called from MapHelper::renderJsContainerMap before MapHelper::renderJsContainerBoundsExtends which adds marker extends is called.

I tried calling fitBounds() after all extends are added and it worked perfectly.

Thanks in advance.

**Comment by davidromani** [comment]
@egeloen sorry, again... my last problem is related with this issue, but in my case I'm using IvoryGoogleMapBundle 3.x

I'm trying this solution https://github.com/egeloen/ivory-google-map/blob/master/doc/map.md#fitting-a-bound-which-extends-overlayslayers but it doesn't works...

**Comment by egeloen** [comment]
Open a new issue please instead of writing on an old issue :) Give me as much informations as possible and I will take a look to it.
