### ISSUE TITLE
Problem with using Autocomplete and Map on same page

### ISSUE THREAD

**Issue by sschueller** [egeloen/ivory-google-map#87]
Is there a way to have both a map with markers etc as well as an autocomplete places form on the same page? I can get either one to work but not together.

I get "Uncaught TypeError: undefined is not a function" which is probably due to a collision. I see the '<script type="text/javascript" src="//www.google.com/jsapi?callback=load_ivory_google_map_api"></script>' is in there twice and a function "function load_ivory_google_map_api ()" is declared twice with different content.

I am using the following on the page:
```
{{ $autocompleteHelper->renderJavascripts($autocomplete) }}
{{ $mapHelper->renderJavascripts($map) }}
```
{{}} are Laravel's blade echo statements.

I am using this in a Laravel project via composer ("egeloen/google-map": "1.4.*@dev")

**Comment by egeloen** [comment]
Your issue has been fixed by #134 but will only be part of the 2.x version.
