### ISSUE TITLE
Map not rendered

### ISSUE THREAD

**Issue by saadel** [egeloen/ivory-google-map#88]
I use the library as standalone and I to rendered a map the map doesn't work all the time, I mean that sometimes it's not working, and sometimes it's working (just in Chrome & Firefox - ironically it works perfect in Internet Explorer) when I inspect the element in Chrome (while the map is not working) it gives me this :
* Failed to load resource: net::ERR_CONNECTION_RESET : http://www.google.com/jsapi?callback=load_ivory_google_map_api
* Uncaught ReferenceError: google is not defined 
* Uncaught TypeError: undefined is not a function

**Comment by egeloen** [comment]
You issue has been fixed by #134 but will only be part of the 2.x version. If the jsapi can' be loaded nothing will be displayed but without errors...
