### ISSUE TITLE
Only one map in foreach.

### ISSUE THREAD

**Issue by RydelHouse** [egeloen/ivory-google-map#89]
Hello,

First of all I would like to say thank you for great library!

But I have some problems. I am using this library to show map for each registered user. But in all user list only one map is showing.

This is my method:

    public function findCompaniesAction() {
        $em = $this->getDoctrine()->getManager();

        $companies = $em->createQueryBuilder()
            ->select('b')
            ->from('RFQIronilBundle:User',  'b')
            ->where('b.acc_type = 1')
            ->getQuery()
            ->getResult();

        foreach ($companies as $key => $company) {
            $map = $this->get('ivory_google_map.map');
            $map->setMapOption('mapTypeId', MapTypeId::ROADMAP);
            $map->setMapOption('mapTypeId', 'roadmap');
            $company->map = $map;
        }

        return $this->render('RFQIronilBundle:Default:find-companies.html.twig', array(
            'companies'     => $companies
        ));
    }

and in my view I use:

{% for companies in companies %}
	{{ google_map_container(companies.map) }}
	{{ google_map_js(companies.map) }}
{% endfor %}

All is fine, but map is showing for only first user. What I have missed?

**Comment by egeloen** [comment]
Your issue has been fixed by #134 but will only be part of the 2.x version.
