### ISSUE TITLE
Get full  geo information from the autocomplete field

### ISSUE THREAD

**Issue by soerenmartius** [egeloen/ivory-google-map#93]
Hi,

for a project i need a places autocomplete field where the user can fill in his whole address. After submitting the form i want to seperate the address in fragments like zipcode, street, city, province etc. At the moment the autocomplete form field only returns the informationen as a string based on the given type. When i render the field with type = geocode, it only returns street + number, city and country.

Is there a way how to solve my problem? Maybe i need an additional geocode request to get the additional data?

Thank you.

**Comment by egeloen** [comment]
You issue has been fixes in #151 but will only be part of the 2.x version.
