### ISSUE TITLE
Map load incorrect if we place it in hidden div (tab)

### ISSUE THREAD

**Issue by biiccs** [egeloen/ivory-google-map#98]
This problems happens if map loading when on load moment he is inside invisible DOM element. I don't find solution for reload map.

Possible solution:
{{ google_map_js(map) }} - generated script like this:
```javascript
<script type="text/javascript">...</script>
```
If this part can be changed to:
```javascript
<script type="text/javascript">
    function init_map_MAPID() {
        ...
    }
    init_map_MAPID();
</script>
```
or something like this, than map can be reloaded when needed with generated function call.

**Comment by egeloen** [comment]
This was a know bug of google map (not sure right now). The solution is to trigger a reload using the map variable. Given your map is named `my_map`, then you can use:

``` php
if (typeof google.maps !== typeof undefined) {
    google.maps.event.trigger(my_map, 'resize');
}
```
