### ISSUE TITLE
Hide markers with javascript?

### ISSUE THREAD

**Issue by jernejpangersic** [egeloen/ivory-google-map#99]
Hi,

I'm using your great bundle to show lots of locations on the map, using markers.
I have about 12 different markers that I'm using.
My question is, if I can some how make a "filter" button, that would hide one of the categories?

For example - I have markers for "Cemeteries". And would like to make a button that would hide/show those locations. Is this possible?

Thanks!

EDIT: Sorry, this should be posted to IvoryGoogleMapBundle repo

**Comment by egeloen** [comment]
Each marker has a javascript variable and you can use this variable in your client side, so if you are able to resolve which marker needs to be hidden, you can hide it with:

```
marker_variable.setMap(null);
```
